before_script:
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 5
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
language: node_js
node_js:
  - "13"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci
  - PORT=3000
cache:
  directories: 
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 5
  - npm run test