language: node_js
node_js:
  - "13"
dist: trusty
sudo: required
services:
  - xvfb
  - mongodb
  - redis-server
env:
  - CHROMIUM=true
  - NODE_ENV=ci
  - PORT=3000
before_install:
  - PUPPETEER_PRODUCT=firefox npm install
cache:
  directories: 
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 5
  - npm run test